import 'package:flutter/material.dart';

class AmTcSection extends StatefulWidget { const AmTcSection({Key? key}) : super(key: key);

@override State<AmTcSection> createState() => _AmTcSectionState(); }

class _AmTcSectionState extends State<AmTcSection> { bool _showTechnologies = false;

void _toggleTechnologies() { setState(() { _showTechnologies = !_showTechnologies; }); }

final List<Map<String, dynamic>> techCategories = [ { 'icon': Icons.computer, 'title': 'Clinical Systems', 'techs': ['Electronic Health Records, Clinical Decision Support', 'Computerized Provider Order Entry', 'Medication Management, Clinical Documentation', 'Care Planning Tools'] }, { 'icon': Icons.factory, 'title': 'Interoperability', 'techs': ['FHIR Implementation', 'HL7 Integration, API Management', 'Health Information Exchange', 'Terminology Services, Data Normalization'] }, { 'icon': Icons.sensors, 'title': 'Data & Analytics', 'techs': ['Clinical Analytics, Population Health', 'Predictive Modeling, Natural Language Processing', 'Machine Learning', 'Real-time Dashboards'] }, { 'icon': Icons.security, 'title': 'Security & Compliance', 'techs': ['HIPAA Compliance', 'Identity and Consent Management', 'Secure Communication', 'Audit Logging, Data Encryption'] }, ];

@override Widget build(BuildContext context) { return Container( color: Colors.grey[100], width: double.infinity, padding: const EdgeInsets.all(16), child: Column( crossAxisAlignment: CrossAxisAlignment.center, children: [ const Text( 'Technologies We Leverage', textAlign: TextAlign.center, style: TextStyle( fontSize: 24, fontWeight: FontWeight.bold, ), ), const SizedBox(height: 12), const Text( 'We employ cutting-edge technologies specifically suited for healthcare applications, ensuring security, compliance, and clinical effectiveness.', textAlign: TextAlign.center, style: TextStyle(fontSize: 16), ), const SizedBox(height: 20), ElevatedButton( onPressed: _toggleTechnologies, style: ElevatedButton.styleFrom( backgroundColor: Colors.blueGrey, shape: RoundedRectangleBorder( borderRadius: BorderRadius.circular(30), ), padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 12), ), child: const Text('Check Our Techstake'), ), const SizedBox(height: 20), if (_showTechnologies) ...techCategories.map((item) { return Container( margin: const EdgeInsets.symmetric(vertical: 10), padding: const EdgeInsets.all(16), decoration: BoxDecoration( borderRadius: BorderRadius.circular(20), color: Colors.white, boxShadow: [ BoxShadow( color: Colors.grey.withOpacity(0.3), blurRadius: 6, offset: const Offset(0, 3), ), ], ), child: Column( crossAxisAlignment: CrossAxisAlignment.start, children: [ Row( children: [ Icon(item['icon'], size: 28, color: Colors.blueGrey), const SizedBox(width: 10), Expanded( child: Text( item['title'], style: const TextStyle( fontSize: 18, fontWeight: FontWeight.w600, ), ), ), ], ), const SizedBox(height: 10), ...item['techs'].map<Widget>((tech) => Padding( padding: const EdgeInsets.symmetric(vertical: 4), child: Row( children: [ const Text('✅️', style: TextStyle(fontSize: 18)), const SizedBox(width: 8), Expanded( child: Text( tech, style: const TextStyle(fontSize: 16), ), ), ], ), )), ], ), ); }).toList() ], ), ); } }