name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.2.5
  flutter_svg: ^2.0.10
  intl: ^0.19.0
  http: ^1.2.1
  visibility_detector: ^0.4.0
  video_player: ^2.8.2



dev_dependencies:
  flutter_test:
    sdk: flutter
  intl: ^0.19.0
  flutter_lints: ^5.0.0
  flutter_svg: ^2.0.9

flutter:
  uses-material-design: true

  assets:
    - assets/logo2.png
    - assets/images/
    - assets/icons/
    - assets/video/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Black.ttf
        - asset: assets/fonts/Inter_18pt-Bold.ttf
          weight: 700
